"""Microsoft Clarity — real session-recording/heatmap analytics for the
storefront (project y9evik4b8h, installed 2026-08-28, see docs/DECISIONS_LOG.md).

Uses Clarity's official Data Export API (REST, Bearer token) — NOT scraping,
NOT a mock. Same honesty convention as finance.py: a source that isn't
connected/authorized is reported with status="not_connected"/"error" and
NEVER faked with a placeholder number (see src/mcp_tools/ads.py for the
anti-pattern this deliberately avoids — that module still returns
deterministic mock metrics, which is why nothing here imports from it).

Needs a Data Export API token, generated by whoever owns the Clarity project:
Clarity dashboard -> Settings -> Data Export -> Add API token. Set it as
CLARITY_API_TOKEN in .env. Without it, every call here returns
status="not_connected" with the exact setup step, never a guessed number.

FIELD-NAME CAVEAT (be honest about what's actually verified): Clarity's
response shape below is built from Clarity's published Data Export API docs,
not a live response — this project's token doesn't exist yet, so the exact
field names in `information` entries per metric have NOT been confirmed
against a real payload this session. `_summarize()` extracts fields
defensively (dict.get with fallbacks, never raises on a missing/renamed
field) and `raw` always carries the untouched response through, specifically
so a schema mismatch degrades to "field not found" rather than a crash or a
silently wrong number. Re-verify field names against the first real response.
"""
from __future__ import annotations

import logging
import os

import httpx

logger = logging.getLogger(__name__)

_API_URL = "https://www.clarity.ms/export-data/api/v1/project-live-insights"
# Clarity's documented limit: 10 requests/project/day, and numOfDays caps at 3
# per request — both enforced here so a caller can't accidentally blow the
# quota (which would then also lock out the periodic report tick).
_MAX_DAYS_PER_REQUEST = 3
_VALID_DIMENSIONS = {"Browser", "Device", "Country/Region", "OS", "Source", "Medium", "Channel"}


def _token() -> str:
    return os.environ.get("CLARITY_API_TOKEN", "").strip()


async def get_clarity_report(
    days: int = 3,
    dimension1: str = "",
    dimension2: str = "",
    dimension3: str = "",
) -> dict:
    """Real Clarity metrics for the last `days` days (1-3 — Clarity's own cap,
    not an arbitrary choice here). Optional dimensions break each metric down
    by up to 3 of: Browser, Device, Country/Region, OS, Source, Medium,
    Channel — pass none for the site-wide totals.

    Returns {"status": "ok", "raw": [...], "summary": {...}} on success,
    {"status": "not_connected", "setup": "..."} if no token is configured,
    or {"status": "error", "detail": "..."} on a real API failure (bad
    token, rate limit, network) — never a guessed number in place of any
    of these.
    """
    token = _token()
    if not token:
        return {
            "status": "not_connected",
            "setup": (
                "No CLARITY_API_TOKEN set. Generate one: Clarity dashboard "
                "(clarity.microsoft.com) -> Settings -> Data Export -> Add API "
                "token -> add it to .env as CLARITY_API_TOKEN."
            ),
        }

    days = max(1, min(int(days), _MAX_DAYS_PER_REQUEST))
    params: dict[str, str] = {"numOfDays": str(days)}
    for i, dim in enumerate((dimension1, dimension2, dimension3), start=1):
        dim = dim.strip()
        if not dim:
            continue
        if dim not in _VALID_DIMENSIONS:
            return {
                "status": "error",
                "detail": f"dimension{i}={dim!r} isn't one of {sorted(_VALID_DIMENSIONS)}",
            }
        params[f"dimension{i}"] = dim

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.get(
                _API_URL, headers={"Authorization": f"Bearer {token}"}, params=params,
            )
    except httpx.HTTPError as exc:
        logger.warning("Clarity Data Export API request failed: %s", exc)
        return {"status": "error", "detail": f"request failed: {exc}"}

    if resp.status_code == 429:
        return {
            "status": "error",
            "detail": (
                "Clarity's 10-requests/project/day limit was hit. Wait for it "
                "to reset rather than retrying now."
            ),
        }
    if resp.status_code != 200:
        return {
            "status": "error",
            "detail": f"Clarity API returned {resp.status_code}: {resp.text[:300]}",
        }

    try:
        raw = resp.json()
    except ValueError:
        return {"status": "error", "detail": f"non-JSON response: {resp.text[:300]}"}

    return {"status": "ok", "raw": raw, "summary": _summarize(raw)}


def _summarize(raw: object) -> dict:
    """Best-effort, crash-proof extraction of the metrics Kai actually reports
    on: real traffic, and the UX-friction signals (dead clicks, rage clicks,
    excessive scroll) that are the whole reason Clarity is worth having. Any
    metric/field not found is simply omitted, not guessed — `raw` above
    always has the untouched response for anything this misses."""
    if not isinstance(raw, list):
        return {}
    by_name = {}
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        name = entry.get("metricName")
        info = entry.get("information")
        if name and isinstance(info, list):
            by_name[name] = info

    def _first_int(info: list, *keys: str) -> int | None:
        for row in info:
            if not isinstance(row, dict):
                continue
            for k in keys:
                if k in row:
                    try:
                        return int(row[k])
                    except (TypeError, ValueError):
                        continue
        return None

    summary: dict = {}
    if "Traffic" in by_name:
        traffic = by_name["Traffic"]
        sessions = _first_int(traffic, "totalSessionCount", "sessionsCount", "totalSessions")
        users = _first_int(traffic, "distinctUserCount", "totalUsers")
        if sessions is not None:
            summary["sessions"] = sessions
        if users is not None:
            summary["distinct_users"] = users
    for metric_name, key in (
        ("DeadClickCount", "dead_clicks"),
        ("RageClickCount", "rage_clicks"),
        ("ExcessiveScroll", "excessive_scroll_sessions"),
        ("QuickbackClick", "quickback_clicks"),
        ("ScriptErrorCount", "script_errors"),
    ):
        if metric_name in by_name:
            val = _first_int(by_name[metric_name], "subTotal", "count", "totalCount")
            if val is not None:
                summary[key] = val
    return summary
