#!/usr/bin/env bash
# Fetch all Alpha Shoop secrets from GCP Secret Manager → local .env
# Usage: bash scripts/fetch-gcp-secrets.sh
# Requires: gcloud CLI authenticated with the right project

set -euo pipefail

PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
if [[ -z "$PROJECT_ID" ]]; then
  echo "✗  No GCP project set. Run: gcloud config set project YOUR_PROJECT_ID"
  exit 1
fi

echo "→ Fetching secrets from project: $PROJECT_ID"

SECRETS=(
  ANTHROPIC_API_KEY
  LITELLM_MASTER_KEY
  SHOPIFY_STORE_DOMAIN
  SHOPIFY_ACCESS_TOKEN
  SHOPIFY_WEBHOOK_SECRET
  CJ_EMAIL
  CJ_API_KEY
  GOOGLE_ADS_DEVELOPER_TOKEN
  GOOGLE_ADS_CUSTOMER_ID
  POSTGRES_PASSWORD
  DATABASE_URL
  REDIS_URL
)

# Backup existing .env
[[ -f .env ]] && cp .env .env.backup && echo "  ✓ Backed up .env → .env.backup"

# Write header
cat > .env << 'ENVHEADER'
# Auto-generated by scripts/fetch-gcp-secrets.sh — do not commit
ENVHEADER

for secret in "${SECRETS[@]}"; do
  secret_name="alpha-shoop-${secret}"
  value=$(gcloud secrets versions access latest \
    --secret="$secret_name" \
    --project="$PROJECT_ID" 2>/dev/null || echo "")

  if [[ -n "$value" ]]; then
    echo "${secret}=${value}" >> .env
    echo "  ✓  ${secret}"
  else
    echo "  ⚠  ${secret} — not found in Secret Manager (skipped)"
  fi
done

echo ""
echo "✓ .env written. Run  docker compose up  to start."
