import { useEffect, useState } from 'react';
import { apiGet, apiPost } from '../api/client';

interface VideoScene {
  order: number;
  voiceover_line: string;
  visual_prompt: string;
  duration_s: number;
}
interface VideoScript {
  product_name: string;
  hook: string;
  scenes: VideoScene[];
  cta: string;
}
interface VideoRow {
  id: string;
  store_id: string;
  shopify_product_id: string;
  product_title: string;
  status: 'rendering' | 'pending_review' | 'approved' | 'rejected' | 'published' | 'failed';
  error: string;
  video_url: string;
  script: VideoScript | null;
  created_at: string | null;
}

// Static video files are served at the API host root (/media/videos/...), not
// under /api/v1 — apiGet's BASE has the /api/v1 suffix, so build this separately.
const MEDIA_BASE = `${window.location.protocol}//${window.location.hostname}:8000`;

const STATUS_STYLE: Record<VideoRow['status'], string> = {
  rendering: 'bg-amber-500/15 text-amber-400',
  pending_review: 'bg-sky-500/15 text-sky-400',
  approved: 'bg-emerald-500/15 text-emerald-400',
  published: 'bg-emerald-500/15 text-emerald-400',
  rejected: 'bg-rose-500/15 text-rose-400',
  failed: 'bg-rose-500/15 text-rose-400',
};

function VideoCard({ video, onDecision }: { video: VideoRow; onDecision: () => void }) {
  const [busy, setBusy] = useState(false);

  async function decide(action: 'approve' | 'reject') {
    setBusy(true);
    try {
      await apiPost(`/videos/${video.id}/${action}`, {});
      onDecision();
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="rounded-xl border border-gray-800 bg-gray-900/60 p-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="font-semibold text-gray-100">{video.product_title}</div>
          <div className="text-xs text-gray-500">{video.store_id} · {video.created_at?.slice(0, 16).replace('T', ' ')}</div>
        </div>
        <span className={`shrink-0 rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_STYLE[video.status]}`}>
          {video.status.replace('_', ' ')}
        </span>
      </div>

      {video.video_url && (
        <video className="mt-3 w-full rounded-lg bg-black" controls src={`${MEDIA_BASE}${video.video_url}`} />
      )}

      {video.script && (
        <div className="mt-3 text-sm text-gray-400">
          <div><span className="text-gray-500">Hook:</span> {video.script.hook}</div>
          <div className="mt-1"><span className="text-gray-500">CTA:</span> {video.script.cta}</div>
        </div>
      )}

      {video.error && <div className="mt-2 text-sm text-rose-400">{video.error}</div>}

      {video.status === 'pending_review' && (
        <div className="mt-3 flex gap-2">
          <button
            disabled={busy}
            onClick={() => decide('approve')}
            className="rounded-lg bg-emerald-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-emerald-500 disabled:opacity-50"
          >
            Approve → publish to Shopify
          </button>
          <button
            disabled={busy}
            onClick={() => decide('reject')}
            className="rounded-lg border border-gray-700 px-3 py-1.5 text-sm font-medium text-gray-300 hover:bg-gray-800 disabled:opacity-50"
          >
            Reject
          </button>
        </div>
      )}
    </div>
  );
}

export function VideosPage() {
  const [videos, setVideos] = useState<VideoRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  function refresh() {
    setLoading(true);
    apiGet<VideoRow[]>('/videos')
      .then((rows) => { setVideos(rows); setError(''); })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }

  useEffect(() => {
    refresh();
    // Rendering can take hours — poll occasionally so a finished render's Slack
    // review state shows up here without a manual page reload.
    const interval = setInterval(refresh, 60_000);
    return () => clearInterval(interval);
  }, []);

  const grouped = videos.reduce<Record<string, VideoRow[]>>((acc, v) => {
    (acc[v.store_id] ??= []).push(v);
    return acc;
  }, {});

  return (
    <div className="p-6">
      <h1 className="text-xl font-bold text-white">Product Ad Videos</h1>
      <p className="mt-1 text-sm text-gray-500">
        Generated by Reel, on request. Review here or in Slack — approving uploads the video to the product on Shopify.
      </p>

      {loading && <div className="mt-6 text-gray-500">Loading…</div>}
      {error && <div className="mt-6 text-rose-400">{error}</div>}
      {!loading && !error && videos.length === 0 && (
        <div className="mt-6 text-gray-500">No videos yet.</div>
      )}

      {Object.entries(grouped).map(([storeId, rows]) => (
        <div key={storeId} className="mt-6">
          <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-gray-500">{storeId}</h2>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            {rows.map((v) => (
              <VideoCard key={v.id} video={v} onDecision={refresh} />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
